dist: trusty
sudo: required

language: python
python:
  - "3.4"

before_install:
  - sudo apt-get update
  # OpenCV installation
  ## packages to build OpenCV
  - sudo apt install build-essential cmake libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt install python3.4-dev libpython3-dev python3-numpy
  - sudo apt install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  ## get the source
  - sudo apt-get install wget zip
  - wget https://github.com/Itseez/opencv/archive/3.1.0.zip
  ## build from source
  - unzip 3.1.0.zip
  - cd opencv-3.1.0
  - mkdir release
  - cd release
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_opencv_java=OFF -D BUILD_opencv_python2=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make
  ## install OpenCV
  - sudo make install
  - cd ../..
  # pygame installation
  ## get source
  - sudo apt-get install mercurial
  - hg clone https://bitbucket.org/pygame/pygame
  ## build pygame
  - sudo apt-get install python3-dev python3-setuptools python3-numpy libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libportmidi-dev libavformat-dev libswscale-dev libjpeg-dev libfreetype6-dev
  - cd pygame
  - python3 setup.py build
  - python3 setup.py install
  - cd ..
  # remaining things
  - sudo apt-get install python3-numpy python3-nose python3-scipy
  - sudo apt-get install libcv2.4 libcvaux2.4 libhighgui2.4 python-opencv libcv-dev libcvaux-dev libhighgui-dev

install: "pip3 install -r requirements.txt"

virtualenv:
  system_site_packages: true

script:
  - cd SimpleCV/tests/
  - nosetests3 -v tests.py
